import { Link } from "react-router-dom";
import { ArrowUpRight } from "lucide-react";

const navigation = [["Work","/portfolio"],["Services","/services"],["Capabilities","/capabilities"],["Process","/process"],["About","/about"],["Contact","/contact"]];
const serviceLinks = [["AI products","/services/ai-products"],["Web & mobile","/services/web-mobile"],["Automation","/services/automation"],["Data & growth","/services/data-growth"]];
const socials = [["LinkedIn","https://www.linkedin.com/company/thinkmoreai"],["Instagram","https://www.instagram.com/thinkmoreai"],["Facebook","https://www.facebook.com/share/1AzqgtTzzJ/"]];

export default function Footer() {
  return <footer className="studio-footer"><div className="studio-container"><div className="studio-footer__grid"><div className="studio-footer__brand"><Link to="/" className="studio-wordmark" aria-label="ThinkMoreAI home"><img src="/thinkmoreai-logo.webp" alt="ThinkMoreAI logo" className="studio-wordmark__logo" width="40" height="40" loading="lazy" /><span className="studio-wordmark__text"><span className="studio-wordmark__title">THINKMORE<span>AI</span></span><span className="studio-wordmark__tagline">Your Vision, Our Execution</span></span></Link><p>We design and engineer intelligent digital systems for businesses with something worth building.</p><Link to="/referral" className="studio-text-link">Referral program <ArrowUpRight size={15}/></Link></div><div><h2>EXPLORE</h2><nav aria-label="Footer navigation">{navigation.map(([label,to])=><Link key={to} to={to}>{label}</Link>)}</nav></div><div><h2>SERVICES</h2><nav aria-label="Service navigation">{serviceLinks.map(([label,to])=><Link key={to} to={to}>{label}</Link>)}</nav></div><div><h2>CONNECT</h2><a href="mailto:info@thinkmoreai.com">info@thinkmoreai.com</a><a href="tel:+919608826629">+91 96088 26629</a><a href="https://cal.id/enquire.thinkmoreai" target="_blank" rel="noopener noreferrer">Book a discovery call ↗</a><div className="studio-footer__social">{socials.map(([label,url])=><a key={label} href={url} target="_blank" rel="noopener noreferrer">{label}</a>)}</div></div></div><div className="studio-footer__bottom"><span>© {new Date().getFullYear()} THINKMOREAI</span><span>ENGINEERED WITH INTENT.</span><div><Link to="/privacy-policy">Privacy</Link><Link to="/terms-of-service">Terms</Link><Link to="/faq">FAQ</Link></div></div></div></footer>;
}
