import LegalDocument, { type LegalSection } from "@/components/LegalDocument";

const sections: LegalSection[] = [
  { id: "scope", title: "Who this policy covers", paragraphs: ["This policy explains how ThinkMoreAI handles personal information shared through this website, including contact enquiries and communications about our services. A separate project agreement may describe additional data handling for a client engagement."] },
  { id: "information", title: "Information we receive", paragraphs: ["When you contact us, we receive the information you choose to provide, such as your name, email address, phone number, service interests, company details, and message. If you email or call us, we receive the information contained in that communication.", "Our hosting and security services may also receive basic technical information needed to deliver the site, such as IP address, browser type, device information, requested pages, and request times."] },
  { id: "use", title: "How we use information", paragraphs: ["We use enquiry details to respond, understand your requirements, prepare proposals, manage a potential or active working relationship, and keep relevant records. Technical information helps us operate, protect, and troubleshoot the website."], bullets: ["Respond to your enquiry and arrange a conversation.", "Plan, deliver, and support agreed services.", "Maintain site performance, security, and business records.", "Comply with applicable legal obligations when required."] },
  { id: "sharing", title: "When information is shared", paragraphs: ["We may share information with providers that help us run the website, communications, and business operations, to the extent needed for those services. We may also disclose information when required by applicable law or to protect our rights. We do not sell enquiry information." ] },
  { id: "cookies", title: "Cookies and external services", paragraphs: ["The website may rely on essential browser storage or technical services for its operation. Links to scheduling, social media, or other external websites open services with their own privacy practices. You can manage browser cookies through your browser settings." ] },
  { id: "retention", title: "Security and retention", paragraphs: ["We take reasonable steps to limit access to personal information and protect it during normal business use. We keep enquiry and project information for as long as reasonably needed for the purpose collected, our working relationship, and applicable record keeping requirements, then delete or anonymize it when appropriate." ] },
  { id: "international", title: "International processing", paragraphs: ["The providers that support our website and communications may process information in the countries where they operate. Where applicable, we take steps required by law for any transfer of personal information across borders."] },
  { id: "children", title: "Children's information", paragraphs: ["This website is intended for business audiences and is not directed at children. If you believe a child has shared personal information with us, contact us so we can review and address it."] },
  { id: "choices", title: "Your choices and requests", paragraphs: ["You can ask us about the personal information we hold, request a correction or deletion, or raise a concern by emailing info@thinkmoreai.com. We will review requests and respond in line with applicable law and any information we need to verify your identity." ] },
  { id: "updates", title: "Changes and contact", paragraphs: ["We may update this policy as our services or practices change. The current version and its update date will be posted here. For privacy questions, contact info@thinkmoreai.com." ] },
];

export default function PrivacyPolicy() {
  return <LegalDocument kind="privacy" title="Privacy Policy" introduction="A clear account of the information you share with us, why we use it, and how to reach us about it." summary={["You choose what to share when you enquire about a project.", "We use your details to respond and manage our working relationship.", "You can contact us to ask about, correct, or request deletion of your information."]} sections={sections}/>;
}
