import LegalDocument, { type LegalSection } from "@/components/LegalDocument";

const sections: LegalSection[] = [
  { id: "acceptance", title: "Using this website", paragraphs: ["These terms apply to your use of the ThinkMoreAI website and its public content. By using the site, you agree to use it lawfully and respect the rights of others. If you do not agree, please discontinue use of the site."] },
  { id: "services", title: "Services and project agreements", paragraphs: ["The site describes our capabilities and examples of work. Service descriptions, timelines, and illustrations are general information, not an offer or guarantee of a particular deliverable. A proposal, statement of work, order, or signed agreement sets the scope, fees, responsibilities, ownership, and delivery terms for a client project. If that agreement conflicts with these website terms, the project agreement governs that project."] },
  { id: "enquiries", title: "Enquiries and information you send", paragraphs: ["Please provide accurate information when contacting us and share only material you are authorized to disclose. Sending an enquiry does not create a client relationship or require either party to proceed with a project. We use enquiry details as described in our Privacy Policy."] },
  { id: "intellectual-property", title: "Website content and intellectual property", paragraphs: ["Unless stated otherwise, the text, design, branding, graphics, and software presented on this website belong to ThinkMoreAI or are used with permission. You may view and share links to public pages for ordinary business evaluation. Reproducing, republishing, or using the site content commercially requires prior written permission.", "Portfolio items marked as concepts or samples are presented as demonstrations of approach; they are not claims of commissioned client work."] },
  { id: "acceptable-use", title: "Acceptable use", paragraphs: ["Do not interfere with the website, attempt unauthorized access, introduce harmful code, scrape the site in a way that disrupts it, or use site content to infringe another person's rights. We may restrict access where needed to protect the site and other visitors."] },
  { id: "external-links", title: "Third-party links", paragraphs: ["The website may link to external platforms, demos, scheduling tools, or social channels. Those services operate under their own terms and policies. We do not control their content or availability."] },
  { id: "availability", title: "Availability and responsibility", paragraphs: ["We work to keep the website useful and accurate, but its content may change and the site may be unavailable at times. Website material is provided for general information. To the extent permitted by applicable law, ThinkMoreAI is not responsible for losses caused by reliance on general site content or interruptions beyond our reasonable control. Nothing here limits rights or obligations that cannot legally be limited."] },
  { id: "updates", title: "Updates and questions", paragraphs: ["We may revise these website terms by publishing an updated version here with a new date. For questions about these terms or a project agreement, contact info@thinkmoreai.com."] },
];

export default function TermsOfService() {
  return <LegalDocument kind="terms" title="Terms of Service" introduction="The ground rules for using this website and understanding how a client project is agreed." summary={["The website explains our capabilities; a written project agreement defines paid work.", "Public concept projects are labeled as demonstrations, not client outcomes.", "Contact us if you need clarification before sharing information or starting a project."]} sections={sections}/>;
}
