export const services = [
  {
    slug: "ai-products",
    number: "01",
    title: "AI products & assistants",
    short: "Intelligence placed inside a useful product workflow.",
    description: "We design assistants and AI features around the decisions people need to make, with clear context, useful responses, and a human path when needed.",
    problem: "Teams often have the information they need, but it is buried across documents, inboxes, and tools. A useful AI product must understand the task, surface the right context, and know when to hand off.",
    approach: "We map the user question and source material first, then design retrieval, response behavior, safeguards, and the interface together.",
    applications: ["Internal knowledge search", "Customer support triage", "Lead qualification"],
    faq: [["Can it work with our existing information?", "That depends on the format, quality, and access rules of the source material. We review those during discovery before recommending a retrieval approach."], ["How are uncertain answers handled?", "The experience should make uncertainty visible and give users a path to a person or verified source when appropriate."]],
    outcome: "Help teams find answers, handle enquiries, and act on information faster.",
    deliverables: ["Knowledge assistants", "AI product features", "Lead and support flows", "Retrieval workflows"],
    technologies: ["OpenAI", "Gemini", "Python", "React"],
    motif: "signal",
  },
  {
    slug: "web-mobile",
    number: "02",
    title: "Web, SaaS & mobile",
    short: "Digital products built to be used, maintained, and extended.",
    description: "From the first user journey to the application layer, we bring product design and engineering into one delivery process.",
    problem: "A new platform can become difficult to use and difficult to extend when design and engineering decisions happen separately.",
    approach: "We define the core journeys, create an interface system, and build the application structure around the first useful release.",
    applications: ["Founder led SaaS", "Commerce experiences", "Mobile product concepts"],
    faq: [["Can you work from an existing product?", "Yes. We start with its current journeys and architecture, then decide what to improve, keep, or rebuild."], ["Do you handle design and engineering?", "We can shape the interface and implement the application in one connected workflow."]],
    outcome: "Launch a coherent product with a dependable foundation for the next release.",
    deliverables: ["Web applications", "SaaS platforms", "Mobile experiences", "Product interfaces"],
    technologies: ["React", "TypeScript", "Node.js", "Flutter"],
    motif: "layers",
  },
  {
    slug: "automation",
    number: "03",
    title: "Automation & integrations",
    short: "Make disconnected tools work as one system.",
    description: "We map repetitive operational work, connect the right systems, and make handoffs visible so teams can spend less time moving information.",
    problem: "Repeated copying, unclear ownership, and disconnected tools create delays that are hard to spot in a busy team.",
    approach: "We trace the workflow from trigger to outcome, design sensible checkpoints, and connect the systems that need to share information.",
    applications: ["Lead intake and routing", "Operational notifications", "Cross tool reporting"],
    faq: [["Can you connect the tools we already use?", "We first check the available APIs, permissions, and reliability needs, then design the integration around those constraints."], ["What happens when an automation fails?", "The workflow should expose errors and create a clear path to recover or hand the task to a person."]],
    outcome: "Reduce manual steps and make critical workflows easier to track.",
    deliverables: ["Workflow mapping", "API integrations", "Lead operations", "Internal reporting"],
    technologies: ["Node.js", "Python", "REST APIs", "Webhooks"],
    motif: "flow",
  },
  {
    slug: "data-growth",
    number: "04",
    title: "Data, analytics & growth",
    short: "Turn scattered signals into clearer decisions.",
    description: "We combine dashboards, research, technical SEO, and content systems to help teams see what is happening and decide what to improve.",
    problem: "Reporting only helps when a team can understand the signal and decide what to do next.",
    approach: "We start with the decision, then shape the data view, research, and content workflow that can support it.",
    applications: ["Decision dashboards", "Market research", "Technical SEO audits"],
    faq: [["What data do you need?", "We begin with the decision the team needs to make, then identify the sources and measures that can answer it."], ["Can this include SEO and content?", "Yes, when search and content are part of the product or growth problem, we can include them in the plan."]],
    outcome: "Give product and commercial teams a clearer view of performance.",
    deliverables: ["Analytics dashboards", "Research & reporting", "Technical SEO", "Content systems"],
    technologies: ["React", "Data visualization", "Technical SEO", "Reporting"],
    motif: "measure",
  },
] as const;

export const projects = [
  {
    slug: "maison-commerce",
    title: "Maison Commerce",
    category: "Commerce experience",
    label: "Concept demo",
    image: "/images/portfolio/maison-interface.jpg",
    url: "https://maison.thinkmoreai.com/",
    challenge: "How should a premium storefront make discovery feel effortless?",
    built: "A commerce concept that puts product imagery, hierarchy, and a clear purchase journey at the center of the experience.",
    features: ["Product discovery", "Commerce UX", "Responsive storefront"],
    technology: ["React", "Commerce UX", "Performance"],
    theme: "copper",
  },
  {
    slug: "nexapay-fintech",
    title: "NexaPay FinTech",
    category: "Mobile product",
    label: "Concept demo",
    image: "/images/portfolio/mobile.webp",
    url: "https://nexapay.thinkmoreai.com/",
    challenge: "How can a payment flow feel clear from the first interaction?",
    built: "A mobile product concept exploring onboarding, account context, and transaction focused navigation.",
    features: ["Onboarding", "Transaction journeys", "Mobile interface"],
    technology: ["Flutter", "Node.js", "Secure APIs"],
    theme: "blue",
  },
  {
    slug: "yumrush-delivery",
    title: "YumRush Delivery",
    category: "Ordering platform",
    label: "Concept demo",
    image: "/images/portfolio/yumrush-live.png",
    url: "https://yumrush.thinkmoreai.com/",
    challenge: "How do customers move from browsing a menu to placing an order with confidence?",
    built: "An ordering and delivery concept organized around menu clarity and visible order progress.",
    features: ["Menu discovery", "Ordering flow", "Order status"],
    technology: ["Vue", "Python", "AWS"],
    theme: "olive",
  },
  {
    slug: "enterprise-saas",
    title: "Enterprise SaaS",
    category: "Product communication",
    label: "Concept demo",
    image: "/images/portfolio/saas.webp",
    url: "https://enterprise.thinkmoreai.com/",
    challenge: "How can a complex product be understood quickly?",
    built: "A SaaS marketing concept with structured product messaging and analytics led framing.",
    features: ["Feature hierarchy", "Product story", "Responsive layout"],
    technology: ["React", "SaaS", "Analytics"],
    theme: "slate",
  },
  {
    slug: "brand-video-production",
    title: "Brand Video Production",
    category: "Video & motion",
    label: "Work sample",
    image: "/images/portfolio/video.webp",
    url: "https://drive.google.com/file/d/134pW1Ai3qzkDdVnT4DAKf_73s0gaW_E8/view?usp=drivesdk",
    challenge: "How can a short visual story hold attention and keep the message clear?",
    built: "A video and motion editing sample for brand and social storytelling.",
    features: ["Motion editing", "Brand story", "Social format"],
    technology: ["Motion", "Video", "Editing"],
    theme: "copper",
  },
  {
    slug: "market-research-report",
    title: "Market Research Report",
    category: "Research & data story",
    label: "Work sample",
    image: "/images/portfolio/Research-report.webp",
    url: "https://drive.google.com/file/d/18U6DK0hfOQD0A4KXeyvBAtGWB_2S7lLS/view?usp=sharing",
    challenge: "How can a report make the next decision easier to see?",
    built: "A research and data storytelling sample structured for concise decision support.",
    features: ["Research", "Charts", "Decision support"],
    technology: ["Research", "Data visualization", "Reporting"],
    theme: "slate",
  },
] as const;
